name: Sysinfo Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sysinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run sysinfo script
        run: python sysinfo.py
